// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeFcZl0s0JJG63mX20pASgIuVTnZ6KOA',
    appId: '1:781835457647:web:dec80d70f956aecb46a99a',
    messagingSenderId: '781835457647',
    projectId: 'namaste-bharat-379d3',
    authDomain: 'namaste-bharat-379d3.firebaseapp.com',
    storageBucket: 'namaste-bharat-379d3.appspot.com',
    measurementId: 'G-LZEZFCYVCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8l8NPfjg51rE9dBsAQjUF-4S3ufxnDZU',
    appId: '1:781835457647:android:d07ca1bc44664e6346a99a',
    messagingSenderId: '781835457647',
    projectId: 'namaste-bharat-379d3',
    storageBucket: 'namaste-bharat-379d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1FoVBE1UEkgfrnB20bdPhGL4yuXa3z04',
    appId: '1:781835457647:ios:61ce9bb74151e4c646a99a',
    messagingSenderId: '781835457647',
    projectId: 'namaste-bharat-379d3',
    storageBucket: 'namaste-bharat-379d3.appspot.com',
    iosBundleId: 'com.example.conPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1FoVBE1UEkgfrnB20bdPhGL4yuXa3z04',
    appId: '1:781835457647:ios:5da34573d627d35b46a99a',
    messagingSenderId: '781835457647',
    projectId: 'namaste-bharat-379d3',
    storageBucket: 'namaste-bharat-379d3.appspot.com',
    iosBundleId: 'com.example.conPractice.RunnerTests',
  );
}
